/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.CatalogoCuentaContable;
import clases.Usuario;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import servicios.Archivos;
import servicios.Convertidor;

/**
 *
 * @author User
 */
public class CatalogoCuentasMantenimiento extends javax.swing.JFrame {

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    /**
     * Creates new form CatalogoCuentasMantenimiento
     */
    public CatalogoCuentasMantenimiento() {
        initComponents();
        
        LocalDate fechaActual = LocalDate.now();
        
        String fechaFormateada = fechaActual.format(formatter);
        
        fecha.setText(fechaFormateada);
        hora.setText(LocalTime.now().toString());
        fecha.disable();
        hora.disable();
        
        tipo.removeAllItems();
        tipo.addItem("General");
        tipo.addItem("Detalle");
        tipo.setSelectedItem("General");
        
        grupo.removeAllItems();
        grupo.addItem("Activo");
        grupo.addItem("Pasivo");
        grupo.addItem("Capital");
        grupo.addItem("Ingresos");
        grupo.addItem("Costos");
        grupo.addItem("Gastos");
        grupo.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        cuentaPadre = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nivel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        credito = new javax.swing.JTextField();
        debito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        fecha = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        grupo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Numero*");

        numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroFocusLost(evt);
            }
        });
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion*");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo*");

        jLabel6.setText("Nivel*");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantenimiento Catalogo de cuentas");

        jLabel7.setText("Cuenta Padre*");

        jLabel4.setText("Fecha creacion*");

        jLabel8.setText("Hora creacion*");

        jLabel9.setText("Grupo*");

        jLabel10.setText("Debito acumulado");

        credito.setEditable(false);

        debito.setEditable(false);

        jLabel11.setText("Credito acumulado");

        balance.setEditable(false);

        jLabel12.setText("Balance");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        label.setText("Creando...");

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nivel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(cuentaPadre)
                            .addComponent(numero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descripcion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(debito)
                            .addComponent(credito)
                            .addComponent(hora)
                            .addComponent(balance)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cuentaPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonRegistrar)
                    .addComponent(actualizar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
    
        if(esValido()){
            
            Archivos manejador = new Archivos();
            
            CatalogoCuentaContable ccc = new CatalogoCuentaContable();
            ccc.Numero = Integer.parseInt(numero.getText());
            ccc.Descripcion = descripcion.getText();
            ccc.Nivel = Integer.parseInt(nivel.getText());
            ccc.Cuenta_padre = Integer.parseInt(cuentaPadre.getText());
            ccc.Grupo = grupo.getSelectedItem().toString();
            ccc.Fecha_creacion = LocalDate.parse(fecha.getText(), formatter);
            ccc.Hora_creacion = LocalTime.parse(hora.getText());
            
            boolean var;
            
            if(tipo.getSelectedItem().toString().equals("General"))
                var = true;
            else
                var = false;
            
            ccc.Tipo_cuenta = var;
       
            if(!debito.getText().isEmpty())
                ccc.Debito_acumulado = Double.parseDouble(debito.getText());
            if(!credito.getText().isEmpty())
                ccc.Credito_acumulado = Double.parseDouble(credito.getText());
            if(!balance.getText().isEmpty())
                ccc.Balance = Double.parseDouble(balance.getText());

            Convertidor cvt = new Convertidor();

            String[] lista = cvt.CatalogoLista(ccc);
            
            if(manejador.ValidarCatalogoCuenta(numero.getText())){
                
                if(ccc.Balance != 0){
                    JOptionPane.showMessageDialog(null, "No se puedo modificar una cuenta con balance", "Informacion", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                    
                
                manejador.Actualizar(manejador.CatalogoCuenta, lista);
                
                JOptionPane.showMessageDialog(null, "Cuenta contable actualizada con exito", "Informacion", JOptionPane.WARNING_MESSAGE);
            }
            else{

                manejador.Insertar(manejador.CatalogoCuenta, lista);
                
                JOptionPane.showMessageDialog(null, "Cuenta contable registrada con exito", "Informacion", JOptionPane.WARNING_MESSAGE);
                
            }
            
            this.Limpiar();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE); 
        }
   
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void Limpiar(){
        
        numero.setText("");
        descripcion.setText("");
        nivel.setText("");
        cuentaPadre.setText("");
        grupo.setSelectedIndex(0);
        debito.setText("");
        credito.setText("");
        balance.setText("");
        tipo.setSelectedItem("General");
        label.setText("Creando...");
        String fechaFormateada = LocalDate.now().format(formatter);
        fecha.setText(fechaFormateada);
        hora.setText(LocalTime.now().toString());
   
    }
    
    private void LimpiarSinCodigo(){
        descripcion.setText("");
        nivel.setText("");
        cuentaPadre.setText("");
        grupo.setSelectedIndex(0);
        debito.setText("");
        credito.setText("");
        balance.setText("");
        tipo.setSelectedItem("General");
    }
    
    
    private boolean esValido(){
        
        if(numero.getText().isEmpty())
            return false;
        if(descripcion.getText().isEmpty())
            return false;
        if(nivel.getText().isEmpty())
            return false;
        if(cuentaPadre.getText().isEmpty())
            return false;
        if(grupo.getSelectedItem().toString().isEmpty())
            return false;
        return true;
    }
    
    private void numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusLost
        
        Archivos manejador = new Archivos();
        
        if(manejador.ValidarCatalogoCuenta(numero.getText())){
            
            Convertidor cvt = new Convertidor();
            CatalogoCuentaContable ccc = new CatalogoCuentaContable();
            ccc = cvt.StringCCC(manejador.ObtenerCCC(numero.getText()));
            
            descripcion.setText(ccc.Descripcion);
            nivel.setText(String.valueOf(ccc.Nivel));
            cuentaPadre.setText(String.valueOf(ccc.Cuenta_padre));
            grupo.setSelectedItem(String.valueOf(ccc.Grupo));
            debito.setText(String.valueOf(ccc.Debito_acumulado));
            credito.setText(String.valueOf(ccc.Credito_acumulado));
            balance.setText(String.valueOf(ccc.Balance));
            
            String var;
            
            if(ccc.Tipo_cuenta)
                var = "General";
            else
                var = "Detalle";
            
            tipo.setSelectedItem(var);
            
            label.setText("Modificando...");
        }
        else{
            label.setText("Creando...");
            LimpiarSinCodigo();
        }
        
    }//GEN-LAST:event_numeroFocusLost

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        
        if(esValido()){
            
            Archivos manejador = new Archivos();
            
            CatalogoCuentaContable ccc = new CatalogoCuentaContable();
            ccc.Numero = Integer.parseInt(numero.getText());
            ccc.Descripcion = descripcion.getText();
            ccc.Nivel = Integer.parseInt(nivel.getText());
            ccc.Cuenta_padre = Integer.parseInt(cuentaPadre.getText());
            ccc.Grupo = grupo.getSelectedItem().toString();
            ccc.Fecha_creacion = LocalDate.parse(fecha.getText(), formatter);
            ccc.Hora_creacion = LocalTime.parse(hora.getText());
            
            boolean var;
            
            if(tipo.getSelectedItem().toString().equals("General"))
                var = true;
            else
                var = false;
            
            ccc.Tipo_cuenta = var;
       
            if(!debito.getText().isEmpty())
                ccc.Debito_acumulado = Double.parseDouble(debito.getText());
            if(!credito.getText().isEmpty())
                ccc.Credito_acumulado = Double.parseDouble(credito.getText());
            if(!balance.getText().isEmpty())
                ccc.Balance = Double.parseDouble(balance.getText());

            Convertidor cvt = new Convertidor();

            String[] lista = cvt.CatalogoLista(ccc);
            
            if(manejador.ValidarCatalogoCuenta(numero.getText())){
                
                if(ccc.Balance != 0){
                    JOptionPane.showMessageDialog(null, "No se puedo modificar una cuenta con balance", "Informacion", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                    
                manejador.Actualizar(manejador.CatalogoCuenta, lista);
                
                JOptionPane.showMessageDialog(null, "Cuenta contable actualizada con exito", "Informacion", JOptionPane.WARNING_MESSAGE);
            }
            else{

                JOptionPane.showMessageDialog(null, "No se puede actualizar un registro que no existe", "Informacion", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            this.Limpiar();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentasMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentasMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentasMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoCuentasMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoCuentasMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField balance;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField credito;
    private javax.swing.JTextField cuentaPadre;
    private javax.swing.JTextField debito;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField fecha;
    private javax.swing.JComboBox<String> grupo;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JTextField nivel;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
