/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.CabeceraTransaccionContable;
import clases.CatalogoCuentaContable;
import clases.TransaccionContable;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import servicios.Archivos;
import servicios.Convertidor;

/**
 *
 * @author User
 */
public class CierreDiarioProceso extends javax.swing.JFrame {

    /**
     * Creates new form CierreDiarioProceso
     */
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    public CierreDiarioProceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaFinal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fechaInicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Cierre diario");

        jLabel2.setText("Fecha inicio");

        jLabel3.setText("Fecha final");

        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Formato de fecha yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(fechaInicio.getText().equals("") || fechaFinal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar ambas fechas", "Informacion", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        LocalDate fecha1 = LocalDate.parse(fechaInicio.getText(), formatter);
        LocalDate fecha2= LocalDate.parse(fechaFinal.getText(), formatter);
        
        if(fecha1.isAfter(fecha2)){
            JOptionPane.showMessageDialog(null, "La fecha de inicio no puede ser mayor a la fecha final", "Informacion", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Archivos manejador = new Archivos();
        Convertidor cvt = new Convertidor();
        
        String[] transacciones = cvt.Separador(manejador.ObtenerDatos(manejador.CabeceraTrans));
        String aux = "";
        
        for(int i=0; i<transacciones.length; i++){
            
            String[] datos = transacciones[i].split("#");
            LocalDate fecha = LocalDate.parse(datos[1], formatter);
            
            if( fecha.isEqual(fecha1) || 
                fecha.isEqual(fecha2) || 
                ((fecha.isAfter(fecha1) && fecha.isBefore(fecha2))) && datos[7].equals("false")){
                aux += datos[0] + "-";
            }
        }
        
        String[] numeros = aux.split("-");
        
        for(int i=0; i<numeros.length; i++){
            
            String[] detalleTransaccion = ObtenerDetalles(cvt.Separador(manejador.ObtenerDatos(manejador.TransacContable)), numeros[i]);

            for(int j=0; j<detalleTransaccion.length; j++){
                
                String numeroCuenta = detalleTransaccion[j].split("#")[2];
                
                ActualizarCuentas(detalleTransaccion[j], manejador.ObtenerCCC(numeroCuenta));
            }
            
            CabeceraTransaccionContable ctc = cvt.StringCTC(manejador.ObtenerCTC(numeros[i]));
            ctc.Fecha_actualizacion = LocalDate.now();
            ctc.Status_actualizacion = true;
            
            manejador.Actualizar(manejador.CabeceraTrans, cvt.CabeceraLista(ctc));
        }

        JOptionPane.showMessageDialog(null, "Proceso culminado con exito", "Informacion", JOptionPane.WARNING_MESSAGE);
        Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Limpiar(){
        fechaInicio.setText("");
        fechaFinal.setText("");
    }
    
    private void ActualizarCuentas(String detalleTransaccion, String detalleCuenta){
        
        Convertidor cvt = new Convertidor();
        Archivos manejador = new Archivos();

        CatalogoCuentaContable cuenta = cvt.StringCCC(detalleCuenta);
        TransaccionContable tc = cvt.StringTC(detalleTransaccion);
        
        cuenta.Debito_acumulado = tc.Valor_debito + cuenta.Debito_acumulado;
        cuenta.Credito_acumulado = tc.Valor_credito + cuenta.Credito_acumulado;
        cuenta.Balance = cuenta.Debito_acumulado - cuenta.Credito_acumulado;
        
        manejador.Actualizar(manejador.CatalogoCuenta, cvt.CatalogoLista(cuenta));
        
        String cuentaPadre = String.valueOf(cuenta.Cuenta_padre);
        
        if(!manejador.ValidarCatalogoCuenta(cuentaPadre))
            return;
        
        ActualizarCuentas(detalleTransaccion, manejador.ObtenerCCC(cuentaPadre));
    }
    
    private String[] ObtenerDetalles(String[] infos, String numero){

        Convertidor cvt = new Convertidor();

        String[] detalles;
        String datos = "";
        
        for(int i=0; i<infos.length; i++){
            
            if(infos[i].split("#")[0].equals(numero)){
                datos += infos[i] + "&";
            }
        }
        
        detalles = cvt.Separador(datos);
        return detalles;
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CierreDiarioProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CierreDiarioProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CierreDiarioProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CierreDiarioProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CierreDiarioProceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaFinal;
    private javax.swing.JTextField fechaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
